# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8090

spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
    
  datasource:    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cust_sys_db
    username: postgres 
    password: postgres
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8

# ENDPOINTS (AbstractEndpoint subclasses)
endpoints:
  enabled: true

# error
#error:
#  whitelabel:
#    enabled: false

settings:
  maxCount: 100

cron:
  cron1: 0 * * * * MON-FRI
  cron2: 0 */2 * * * *
